FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt gunicorn
COPY app/frontend.py .
COPY app/templates ./templates 
CMD [ "gunicorn", "--bind", "0.0.0.0:5001", "frontend:app"]
